// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzucecqyxrzxmhkpotnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dWNlY3F5eHJ6eG1oa3BvdG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDU3MzEsImV4cCI6MjA2Njk4MTczMX0.PSm33K3Og0UKmr3SPJ5peCMM7R35viuglPIcoZTL42o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});